language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t marjugoncalves/multi-container-end-to-end-pipeline -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true marjugoncalves/multi-container-end-to-end-pipeline npm run test -- --coverage --watchAll=false

after_success:
  - docker build -t marjugoncalves/multi-client ./client
  - docker build -t marjugoncalves/multi-nginx ./nginx
  - docker build -t marjugoncalves/multi-server ./server
  - docker build -t marjugoncalves/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push marjugoncalves/multi-client
  - docker push marjugoncalves/multi-nginx
  - docker push marjugoncalves/multi-server
  - docker push marjugoncalves/multi-worker


deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-services-app'
  env: 'Multiservicesapp-env'
  bucket_name: 'elasticbeanstalk-us-east-2-389082447763'
  bucket_path: 'multi-services-app'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
                                    